### ISSUE TITLE
issue with linkcheck

### ISSUE THREAD

**Issue by mittelma** [filiph/linkcheck#121]
FormatException: Could not find an option named "no-warnings".
#0      Parser._validate (package:args/src/parser.dart:309)
#1      Parser._handleLongOption (package:args/src/parser.dart:287)
#2      Parser._parseLongOption (package:args/src/parser.dart:262)
#3      Parser.parse (package:args/src/parser.dart:86)
#4      ArgParser.parse (package:args/src/arg_parser.dart:334)
#5      run (package:linkcheck/linkcheck.dart:203)
#6      main.<anonymous closure> (file:///home/runner/work/linkcheck/linkcheck/bin/linkcheck.dart:9)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1293)
#9      _runZoned (dart:async/zone.dart:1829)
#10     runZonedGuarded (dart:async/zone.dart:1817)
#11     main (file:///home/runner/work/linkcheck/linkcheck/bin/linkcheck.dart:7)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

**Comment by parlough** [comment]
Hi @mittelma, thanks for opening an issue! 

Could you provide some details about how you're running `linkcheck` and where you learned about a `no-warnings` option? As far as I can tell, there isn't a `no-warnings` option nor has there even been.

**Comment by mittelma** [comment]
I found it.
