### ISSUE TITLE
Unhandled exception always on the same external site

### ISSUE THREAD

**Issue by mmattel** [filiph/linkcheck#38]
Running linkcheck on a local site build including external links to be checked,
I always get an unhandled exception on the same external page, see below:

```
linkcheck -e --skip-file ../my_skip_file.txt --no-connection-failures-as-warnings > ../linkchecker.log 

Unhandled exception:
HttpException: Connection closed while receiving data, uri = https://jira.mariadb.org/robots.txt
#0      checkServer (package:linkcheck/src/worker/worker.dart:81:15)
<asynchronous suspension>
#1      worker.<anonymous closure> (package:linkcheck/src/worker/worker.dart:199:42)
<asynchronous suspension>
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#6      _StreamController._add (dart:async/stream_controller.dart:640:7)
#7      _StreamController.add (dart:async/stream_controller.dart:586:5)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#11     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#12     _StreamController._add (dart:async/stream_controller.dart:640:7)
#13     _StreamController.add (dart:async/stream_controller.dart:586:5)
#14     _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#21     _StreamController._add (dart:async/stream_controller.dart:640:7)
#22     _StreamController.add (dart:async/stream_controller.dart:586:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
INTERNAL ERROR: Sorry! Please open https://github.com/filiph/linkcheck/issues/new in your favorite browser and copy paste the following output there:

Bad state: No element
```

**Comment by filiph** [comment]
Sorry for not seeing this earlier. Could you please try with the latest version? `pub global activate linkcheck` should give you 2.0.8.

That will probably not help but it's a start.

**Comment by mmattel** [comment]
Here we go. Failing (but continues) on the same link
```
linkcheck -v
linkcheck version 2.0.8
```
```
linkcheck -e --skip-file ../my_skip_file.txt --no-connection-failures-as-warnings > ../linkcheck.log

Unhandled exception:
HttpException: Connection closed while receiving data, uri = https://jira.mariadb.org/robots.txt
#0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:161:7)
#1      _invokeErrorHandler (dart:async/async_error.dart:17:29)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1326:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
#8      _SyncStreamController._sendError (dart:async/stream_controller.dart:768:19)
#9      _StreamController._addError (dart:async/stream_controller.dart:648:7)
#10     _StreamController.addError (dart:async/stream_controller.dart:600:5)
#11     _HttpParser._onDone (dart:_http/http_parser.dart:822:25)
#12     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#16     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#17     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#18     _StreamController.close (dart:async/stream_controller.dart:622:5)
#19     _Socket._onData (dart:io-patch/socket_patch.dart:1781:21)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#24     _StreamController._add (dart:async/stream_controller.dart:640:7)
#25     _StreamController.add (dart:async/stream_controller.dart:586:5)
#26     _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:797:21)
#27     _RawSecureSocket._tryFilter.<anonymous closure> (dart:io/secure_socket.dart:919:11)
#28     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

And many thanks for that great program !

**Comment by mmattel** [comment]
May I ask for a favour.
When doing a new release, it would be helpful to have in `--help` the output how to upgrade. Text is totally fine like: In case you want to upgrade run following command: `pub global activate linkcheck`. Without your comment above, I would not have known how to do that as I am not fimilar with dart...
