### ISSUE TITLE
FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)

### ISSUE THREAD

**Issue by nank1ro** [filiph/linkcheck#52]
FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:879)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:344)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
#8      _StreamController._add (dart:async/stream_controller.dart:640)
#9      _StreamController.add (dart:async/stream_controller.dart:586)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:156)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:289)
#12     _IOSinkImpl.writeln (dart:io/io_sink.dart:309)
#13     _StdSink.writeln (dart:io/stdio.dart:341)
#14     crawl.print (package:linkcheck/src/crawl.dart:37)
#15     crawl.<anonymous closure> (package:linkcheck/src/crawl.dart:133)
#16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43)
#17     crawl.<anonymous closure> (package:linkcheck/src/crawl.dart:123)
#18     _rootRunUnary (dart:async/zone.dart:1132)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#22     _DelayedData.perform (dart:async/stream_impl.dart:591)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1021)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#29     _rootRun (dart:async/zone.dart:1124)
#30     _CustomZone.run (dart:async/zone.dart:1021)
#31     _CustomZone.runGuarded (dart:async/zone.dart:923)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173)

Unhandled exception:
HttpException: Connection closed while receiving data, uri = https://hidden_website.com
#0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:161)
#1      _invokeErrorHandler (dart:async/async_error.dart:17)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1326)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272)
#8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:768)
#9      _StreamController._addError (dart:async/stream_controller.dart:648)
#10     _StreamController.addError (dart:async/stream_controller.dart:600)
#11     _HttpParser._onDone (dart:_http/http_parser.dart:822)
#12     _RootZone.runGuarded (dart:async/zone.dart:1302)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283)
#16     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772)
#17     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629)
#18     _StreamController.close (dart:async/stream_controller.dart:622)
#19     _Socket._onDone (dart:io-patch/socket_patch.dart:1844)
#20     _RootZone.runGuarded (dart:async/zone.dart:1302)
#21     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389)
#22     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#23     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283)
#24     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772)
#25     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629)
#26     _StreamController.close (dart:async/stream_controller.dart:622)
#27     _RawSecureSocket._close (dart:io/secure_socket.dart:648)
#28     _RawSecureSocket.shutdown (dart:io/secure_socket.dart:670)
#29     _RawSecureSocket.close (dart:io/secure_socket.dart:623)
#30     _Socket._closeRawSocket (dart:io-patch/socket_patch.dart:1800)
#31     _Socket.destroy (dart:io-patch/socket_patch.dart:1732)
#32     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1817)
#33     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#34     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#35     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#36     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#37     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#38     _ConnectionTarget.close (dart:_http/http_impl.dart:1955)
#39     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#40     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#41     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#42     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#43     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#44     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#45     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#46     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#47     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#48     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#49     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#50     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#51     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#52     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#53     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#54     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#55     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#56     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#57     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#58     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#59     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#60     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#61     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#62     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#63     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#64     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#65     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#66     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#67     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#68     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#69     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#70     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#71     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#72     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#73     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#74     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#75     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#76     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#77     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#78     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#79     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#80     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#81     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#82     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#83     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#84     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#85     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#86     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#87     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#88     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#89     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#90     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#91     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#92     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#93     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#94     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#95     _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#96     _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#97     _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#98     _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#99     _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#100    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#101    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#102    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#103    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#104    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#105    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#106    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#107    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#108    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#109    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#110    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#111    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#112    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#113    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#114    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#115    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#116    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#117    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#118    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#119    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#120    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#121    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#122    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#123    _ConnectionTarget.close (dart:_http/http_impl.dart:1955)
#124    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#125    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#126    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#127    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#128    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#129    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#130    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#131    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#132    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#133    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#134    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#135    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#136    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#137    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#138    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#139    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#140    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#141    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#142    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#143    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#144    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#145    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#146    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#147    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#148    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#149    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#150    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#151    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#152    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#153    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#154    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#155    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#156    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#157    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#158    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#159    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#160    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#161    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#162    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#163    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#164    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#165    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#166    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#167    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#168    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#169    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#170    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#171    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#172    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#173    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#174    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#175    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#176    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#177    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#178    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#179    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#180    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#181    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#182    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#183    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#184    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#185    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#186    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#187    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#188    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#189    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#190    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#191    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#192    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#193    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#194    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#195    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#196    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#197    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#198    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#199    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#200    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#201    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#202    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#203    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#204    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#205    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#206    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#207    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#208    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#209    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#210    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#211    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#212    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#213    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#214    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#215    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#216    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#217    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#218    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#219    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#220    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#221    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#222    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#223    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#224    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#225    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#226    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#227    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#228    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#229    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#230    _HttpClient._connectionsChanged (dart:_http/http_impl.dart:2275)
#231    _HttpClient._connectionClosed (dart:_http/http_impl.dart:2269)
#232    _HttpClientConnection.destroy (dart:_http/http_impl.dart:1816)
#233    _ConnectionTarget.close (dart:_http/http_impl.dart:1958)
#234    _HttpClient._closeConnections (dart:_http/http_impl.dart:2281)
#235    _HttpClient.close (dart:_http/http_impl.dart:2152)
#236    worker.<anonymous closure> (package:linkcheck/src/worker/worker.dart:186)
#237    _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43)
#238    worker.<anonymous closure> (package:linkcheck/src/worker/worker.dart:183)
#239    _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#240    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#241    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#242    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
#243    _StreamController._add (dart:async/stream_controller.dart:640)
#244    _StreamController.add (dart:async/stream_controller.dart:586)
#245    _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#246    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#247    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#248    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
#249    _StreamController._add (dart:async/stream_controller.dart:640)
#250    _StreamController.add (dart:async/stream_controller.dart:586)
#251    _StreamSinkWrapper.add (dart:async/stream_controller.dart:858)
#252    _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#253    CastStreamSubscription._onData (dart:_internal/async_cast.dart:81)
#254    _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#255    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#256    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#257    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
#258    _StreamController._add (dart:async/stream_controller.dart:640)
#259    _StreamController.add (dart:async/stream_controller.dart:586)
#260    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

**Comment by filiph** [comment]
I'm sorry, I cannot reproduce this. Could you please share a bit more info about your setup (operating system, the kind of server you're trying to linkcheck, etc.)?
