### ISSUE TITLE
internal error in _RawReceivePortImpl

### ISSUE THREAD

**Issue by oboehmer** [filiph/linkcheck#63]
Hey.. thanks for your great tool which we're using in an internal pipeline to check our documentation.. Today we noticed the following failure in a docker container built off  google/dart with `RUN pub global activate linkcheck` crawling an adjacent container web server.
 
This error seems to be intermittent, can't give more info than provided in below:

```
+ docker-compose -f docker-compose-utils.yml run linkcheck bash -c linkcheck --no-nice --skip-file jenkins/linkcheck-ignore http://cxta_docs_ext:8080

Creating cxta_docs_ext ... 
Creating cxta_docs_ext ... done
Crawling...
INTERNAL ERROR: Sorry! Please open https://github.com/filiph/linkcheck/issues/new in your favorite browser and copy paste the following output there:

Bad state: No element

#0      SetMixin.singleWhere (dart:collection/set.dart:267:5)
#1      crawl.<anonymous closure> (package:linkcheck/src/crawl.dart:255:20)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#9      _rootRun (dart:async/zone.dart:1182:47)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by filiph** [comment]
Ooof, this took way longer than I anticipated, but it's finally fixed in version `2.0.15`. If things don't work as expected, please run linkcheck with `--verbose` and paste the output here. Thanks for the patience!
